create table if not exists app_user (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    email varchar(255) not null,
    passwordHash varchar(255) not null,
    role varchar(255) not null,
    createdAt timestamp(6) with time zone not null,
    constraint uk_app_user_username unique (username),
    constraint uk_app_user_email unique (email)
);

create table if not exists Recipe (
    id bigint generated by default as identity primary key,
    title varchar(500),
    imageUrl varchar(2048),
    prepTimeMinutes integer not null,
    cookTimeMinutes integer not null,
    servings integer not null,
    difficulty varchar(255),
    category varchar(255),
    rating double precision not null,
    ingredients text,
    instructions text,
    favorite boolean not null,
    published boolean not null,
    calories integer,
    protein double precision,
    alcohol double precision,
    alcohol_percent double precision,
    external_id varchar(255),
    source_url varchar(2048),
    source_name varchar(255),
    dish_types text,
    diets text,
    vegetarian boolean not null,
    vegan boolean not null,
    gluten_free boolean not null,
    dairy_free boolean not null,
    language varchar(255),
    owner_id bigint,
    constraint fk_recipe_owner foreign key (owner_id) references app_user (id)
);

create table if not exists ExternalRecipeFavorite (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    external_recipe_id varchar(80) not null,
    external_title varchar(255) not null,
    external_image_url varchar(1000),
    external_source varchar(40) not null,
    createdAt timestamp(6) with time zone not null,
    constraint fk_external_recipe_favorite_owner foreign key (owner_id) references app_user (id),
    constraint uk_external_recipe_favorite_owner_source_id unique (owner_id, external_source, external_recipe_id)
);

create table if not exists MealPlan (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    recipe_id bigint,
    custom_title varchar(160),
    calories_snapshot integer,
    protein_snapshot double precision,
    image_url_snapshot varchar(1000),
    external_recipe_id varchar(100),
    external_source varchar(80),
    planned_date date not null,
    meal_slot varchar(255),
    createdAt timestamp(6) with time zone not null,
    updatedAt timestamp(6) with time zone not null,
    constraint fk_meal_plan_owner foreign key (owner_id) references app_user (id),
    constraint fk_meal_plan_recipe foreign key (recipe_id) references Recipe (id),
    constraint uk_meal_plan_owner_planned_date_slot unique (owner_id, planned_date, meal_slot)
);

create table if not exists PantryItem (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    quantity numeric(38, 2) not null,
    unit varchar(255),
    category varchar(255),
    owner_id bigint not null,
    createdAt timestamp(6) with time zone not null,
    updatedAt timestamp(6) with time zone not null,
    constraint fk_pantry_item_owner foreign key (owner_id) references app_user (id)
);

create table if not exists ShoppingListItem (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    quantity numeric(38, 2),
    unit varchar(255),
    category varchar(255),
    recipeId varchar(255),
    recipeTitle varchar(255),
    checked boolean not null,
    owner_id bigint not null,
    createdAt timestamp(6) with time zone not null,
    updatedAt timestamp(6) with time zone not null,
    constraint fk_shopping_list_item_owner foreign key (owner_id) references app_user (id)
);

create table if not exists user_preferences (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    vegan boolean not null,
    vegetarian boolean not null,
    glutenFree boolean not null,
    lactoseFree boolean not null,
    highProtein boolean not null,
    calorieConscious boolean not null,
    budgetFriendly boolean not null,
    maxPrepTimeMinutes integer,
    calorieGoal integer,
    goal varchar(255) not null,
    dailyCalorieTarget integer,
    createdAt timestamp(6) with time zone not null,
    updatedAt timestamp(6) with time zone not null,
    constraint fk_user_preferences_owner foreign key (owner_id) references app_user (id),
    constraint uk_user_preferences_owner unique (owner_id)
);

create table if not exists user_preference_likes (
    preferences_id bigint not null,
    value varchar(255) not null,
    constraint fk_user_preference_likes_preferences foreign key (preferences_id) references user_preferences (id)
);

create table if not exists user_preference_dislikes (
    preferences_id bigint not null,
    value varchar(255) not null,
    constraint fk_user_preference_dislikes_preferences foreign key (preferences_id) references user_preferences (id)
);

create table if not exists user_preference_allergies (
    preferences_id bigint not null,
    value varchar(255) not null,
    constraint fk_user_preference_allergies_preferences foreign key (preferences_id) references user_preferences (id)
);

create index if not exists idx_recipe_language_published on Recipe (language, published);
create index if not exists idx_recipe_owner on Recipe (owner_id);
create index if not exists idx_meal_plan_owner_date on MealPlan (owner_id, planned_date);
create index if not exists idx_pantry_item_owner on PantryItem (owner_id);
create index if not exists idx_shopping_list_item_owner on ShoppingListItem (owner_id);
